### ISSUE TITLE
Refactorer la restitutions des questions sur le modèle de Livraison et Bienvenue

### ISSUE THREAD

**Issue by shanser** [betagouv/eva-serveur#414]
Voir ce qui a été fait dans #413

**Comment by Laurenmichel21** [comment]
@shanser je ne comprends pas ce qu'il y a à recetter. Est ce que l'on peut partir du principe que c'est du dèv et que c'est bon ? Ou bien cela nécessite t-il une validation "métier" ? Merci pour ton éclairage.

**Comment by shanser** [comment]
bonne remarque, c'est un sujet purement technique. Du coup j'ai rajouté un tag comme ça c'est visible qu'il n'y a pas besoin de recetter côté métier ;-)
