### ISSUE TITLE
Connaitre facilement le nombre de passation d'une structure

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva-serveur#423]
De même que pour l'issue betagouv/eva#942, cette information pourrait être affichée dans la page d'admin des structures (qu'il faut créer)

**Comment by shanser** [comment]
![Capture d’écran 2020-05-06 à 10 17 35](https://user-images.githubusercontent.com/28393/81153327-19873300-8f83-11ea-8e80-a0e834033731.png)

**Comment by Laurenmichel21** [comment]
Est ce que cela signifie qu'il faut faire une reprise de stock de tous les comptes déjà enregistré pour pouvoir avoir cette donnée  ?

**Comment by shanser** [comment]
Il faut créer toutes les structures et affecter les comptes aux bonne structures. 
Ensuite le calcul se fait automatiquement et prend en compte toutes les passassions depuis le début.

PS : Je suppose que tu as bloqué pour signaler ton commentaire. Du coup j'enlève le tag, je te laisse le remettre si c'était pour une autre raison.

**Comment by Laurenmichel21** [comment]
N'avez vous pas moyen de le faire techniquement et de l'automatiser ?  cette donnée ne pouvait elle pas être, elle aussi intégrée directement dans la page " compte" en y ajoutant simplement une colonne supplémentaire. Toujours dans cet objectif de simplification :-) 
Si ce n'est pas possible je vous propose que l'on se répartisse les saisies  dev et métier 
 cc @laurenehoutin

**Comment by etienneCharignon** [comment]
La création de toutes les structures déjà existantes automatiquement est l'objet de l'issue  betagouv/eva-serveur#426
