### ISSUE TITLE
Cas de non persistance des métriques de livraison

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva-serveur#428]
Pour l'évaluation suivante :

https://api.app.eva.beta.gouv.fr/admin/campagnes/5515a126-f7fb-4b6d-a7dc-93557ee8939b/evaluations/6d24ac5f-9305-4471-8d02-35be225d173b

pour la situation Livraison, 
Les métriques sont bien calculées puisqu'elles s'affichent dans le rapport mais elles ne sont pas écrites en base dans la table Partie.

Pour information, cette évaluation n'a pas les événements "affichageQuestionQCM"

**Comment by shanser** [comment]
Effectivement, c'est intéressant comme cas. 
Est-ce qu'on veut qu'il soit persisté ?

Je vois deux approches 

- Puisqu'il n'y a pas les événements `affichageQuestionQCM`, on ne peut pas comparer correctement avec les autres, donc autant ne pas le mettre
- Ou au contraire on veut les garder et on définit une règle du genre "on part du principe que la question s'est affichée XXXms après la réponse

Dans le dernier cas, je privilégierai le fait d'ajouter les événements dans la base afin d'harmoniser nos données.

**Comment by shanser** [comment]
Cette ligne https://github.com/betagouv/eva-serveur/blob/develop/app/admin/situations.rb#L26 empêche de persister.

**Comment by etienneCharignon** [comment]
Pour mémoire, voici aujourd'hui le pourcentage de présence de métriques par situation

<img width="422" alt="Capture d’écran 2020-05-12 à 10 45 09" src="https://user-images.githubusercontent.com/298214/81665539-1c7d9a00-9441-11ea-95c3-37082ccc5c8f.png">
