### ISSUE TITLE
Admin, je peux saisir les informations de la structure avec celles du compte afin de minimiser mes manipulations

### ISSUE THREAD

**Issue by shanser** [betagouv/eva-serveur#429]
pour faire suite à la remarque de Lauren dans ce commentaire : https://github.com/betagouv/eva/issues/942#issuecomment-624852256

> J'ai une question : est ce qu'il n'était pas du tout possible d'intégrer le champ code postal au moment de la création du compte comme initialement demandé ? Car cela nous fait faire trois manipulation
> 
> je crée la structure
> Je crée le compte
> je crée la campagne
> Et quand on n'en a une dizaine à créer c'est pas ce qu'il y a de plus simplifiant ;-)

**Comment by etienneCharignon** [comment]
Ce que je propose c'est que l'écran de création des structures demande toute les informations et créé en un coup, la structure, un compte et une campagne.

C'est mieux si ça se passe dans l'écran de création de la structure, plutôt que celui de la création du compte car on veut pouvoir créer des comptes seul (comme les comptes d'administrations) et j'anticipe qu'on voudra ajouter des comptes à une structures.

**Comment by etienneCharignon** [comment]
avec #445 on a déjà un premier formulaire. Reste à ajouter encore l'initialisation par défaut des campagne (travail en cours).
