### ISSUE TITLE
Administrateur, je peux voir les situations complétées vs les situations démarrées afin de me rendre compte du taux de complétion

### ISSUE THREAD

**Issue by shanser** [betagouv/eva-serveur#435]

**Comment by etienneCharignon** [comment]
La requête "Nombre de passations terminées dans les structures par situation" suppose qu'il n'y a qu'un seul événement fin (cf remarque https://github.com/betagouv/eva-serveur/pull/434#issuecomment-627228691)

**Comment by shanser** [comment]
oui je l'avais en tête. on a globalement des données à nettoyer à mon avis.

**Comment by shanser** [comment]
J'ai fait évolué l'autre PR, j'ai vérifié en prod il y avait 2 situations qui avaient 2 événements fin. J'ai supprimé le doublon.

**Comment by etienneCharignon** [comment]
L'admin contient maintenant trois graphiques : 
- Nombre de passations démarrées dans les structures par situation
- Nombre de passations terminées dans les structures par situation
- Nombre de passations, terminées ou pas, dans les structures par situation (qui est l'affichage sur un seul graphique des deux précédents)

**Comment by etienneCharignon** [comment]
J'ai l'impression qu'avec ces 3 indicateurs, cette issue est terminée.
