### ISSUE TITLE
traiter le problème rails Deprecation warning : Initialization autoloaded constants

### ISSUE THREAD

**Issue by etienneCharignon** [betagouv/eva-serveur#473]
J'ai l'impression que le problème vient d'un des initializer de ActiveAdmin qui preload des constantes (de manière indirecte).

J'ai trouvé plusieurs éléments que je mets ici pour mémoire : 

https://stackoverflow.com/questions/56402093/how-can-i-preload-concerns-in-a-rails-initializer-using-rails-6-zeitwerk

https://github.com/activeadmin/activeadmin/issues/5772

**Comment by shanser** [comment]
elle est reportée dans Trello
https://trello.com/c/zQEeH6LP/537-traiter-le-probl%C3%A8me-rails-deprecation-warning-initialization-autoloaded-constants
